# Generated by Django 5.1.7 on 2025-03-14 10:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="ActionType",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="Unikátní název typu akce.",
                        max_length=50,
                        unique=True,
                        verbose_name="Název typu",
                    ),
                ),
            ],
            options={
                "verbose_name": "Typ akce",
                "verbose_name_plural": "Typy akcí",
            },
        ),
        migrations.CreateModel(
            name="Action",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="Zadejte název akce.",
                        max_length=255,
                        verbose_name="Název akce",
                    ),
                ),
                (
                    "type",
                    models.ForeignKey(
                        help_text="Vyberte typ akce.",
                        on_delete=django.db.models.deletion.CASCADE,
                        to="storage.actiontype",
                        verbose_name="Typ akce",
                    ),
                ),
            ],
            options={
                "verbose_name": "Akce",
                "verbose_name_plural": "Akce",
            },
        ),
    ]
