# Generated by Django 5.1.7 on 2025-03-14 11:43

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("storage", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="UploadedFile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "author",
                    models.CharField(
                        help_text="Autor souboru.", max_length=255, verbose_name="Autor"
                    ),
                ),
                (
                    "stored_file",
                    models.FileField(
                        help_text="Nahraný soubor.",
                        upload_to="uploads/%Y/%m/",
                        verbose_name="Soubor",
                    ),
                ),
                (
                    "uploaded_at",
                    models.DateTimeField(
                        auto_now_add=True,
                        help_text="Datum a čas, kdy byl soubor nahrán.",
                        verbose_name="Datum nahrání",
                    ),
                ),
                (
                    "is_public",
                    models.BooleanField(
                        default=False,
                        help_text="Určuje, zda je soubor veřejně dostupný.",
                        verbose_name="Veřejný přístup",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        help_text="Uživatel, který soubor nahrál.",
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Uživatel",
                    ),
                ),
            ],
            options={
                "verbose_name": "Nahraný soubor",
                "verbose_name_plural": "Nahrané soubory",
            },
        ),
    ]
