# Generated by Django 5.1.7 on 2025-03-27 07:58

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("storage", "0002_uploadedfile"),
    ]

    operations = [
        migrations.AlterField(
            model_name="uploadedfile",
            name="id",
            field=models.UUIDField(
                default=uuid.uuid4,
                editable=False,
                primary_key=True,
                serialize=False,
                verbose_name="UUID",
            ),
        ),
    ]
