name: Django CI

on:
  push:
    branches: [ "*" ]
  pull_request:
    branches: [ "*" ]

env:
  DJANGO_SECRET_KEY: ${{ secrets.DJANGO_SECRET_KEY }}
  DJANGO_DEBUG:  ${{ secrets.DJANGO_DEBUG }}
  DJANGO_ALLOWED_HOSTS:  ${{ secrets. DJANGO_ALLOWED_HOSTS }}
  DJANGO_DATABASE_ENGINE:  ${{ secrets.DJANGO_DATABASE_ENGINE }}
  DJANGO_DATABASE_NAME:  ${{ secrets.DJANGO_DATABASE_NAME }}
  DJANGO_LANGUAGE_CODE:  ${{ secrets.DJANGO_LANGUAGE_CODE }}
  DJANGO_TIME_ZONE:  ${{ secrets.DJANGO_TIME_ZONE }}
  DJANGO_STATIC_URL: ${{ secrets.DJANGO_STATIC_URL }}
  DJANGO_STATIC_ROOT: ${{ secrets.DJANGO_STATIC_ROOT }}
  DJANGO_MEDIA_URL: ${{ secrets.DJANGO_MEDIA_URL }}
  DJANGO_MEDIA_ROOT: ${{ secrets.DJANGO_MEDIA_ROOT }}
  DOWNLOAD_URL: ${{ secrets.DJANGO_URL }}


jobs:
  build:

    runs-on: ubuntu-latest
    strategy:
      max-parallel: 4
      matrix:
        python-version: [3.11, 3.12, 3.13]

    steps:
    - uses: actions/checkout@v4
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v3
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install Dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    - name: Run Tests
      run: |
        python manage.py test
  
    - name: Run makemigrations check
      run: python manage.py makemigrations --check --dry-run
    
    - name: Run migrate
      run: python manage.py migrate --noinput